name: 'AutoCoder'
description: 'This action automates the process of generating code from GitHub issues using OpenAIs ChatGPT and subsequently creates a pull request with the generated code for review.'
author: 'Your Name or Organization'

inputs:
  GITHUB_TOKEN:
    description: 'Personal access token (PAT) used for GitHub API authentication. This token is required to create pull requests and handle other repository interactions.'
    required: true
  OPENAI_API_KEY:
    description: 'API key for OpenAI, enabling interactions with the ChatGPT service to generate code based on issue descriptions.'
    required: true
  LABEL:
    description: 'The label assigned to GitHub issues that should be processed by the AutoCoder action. Only issues with this label will trigger the code generation process.'
    required: true
    default: 'autocoder-bot'
  SCRIPT_PATH:
    description: 'Path to the script that interacts with ChatGPT'
    required: true
    default: 'scripts/script.sh'
  REPOSITORY:
    description: 'Repository where the action is executed'
    required: true
  ISSUE_NUMBER:
    description: 'The number of the issue that triggered the action'
    required: true

outputs:
  pull_request_url:
    description: 'The URL of the pull request that has been automatically created, containing the auto-generated code for review and potential merging.'

runs:
  using: 'composite'
  steps:
    - name: Greet Users
      run: echo "Hello, welcome to AutoCoder! Let's generate some code."
      shell: bash

    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Generate Code from Issue
      run: |
        # The script that interacts with ChatGPT and generates code goes here.
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
        ISSUE_NUMBER: ${{ inputs.ISSUE_NUMBER }}
        REPOSITORY: ${{ inputs.REPOSITORY }}

    - name: Make script executable
      run: chmod +x ${{ inputs.SCRIPT_PATH }}
      shell: bash
    
    - name: Interact with ChatGPT and Generate Code
      id: generate_code
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        REPOSITORY: ${{ inputs.REPOSITORY }}
        ISSUE_NUMBER: ${{ inputs.ISSUE_NUMBER }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
      run: |
        ${{ inputs.SCRIPT_PATH }} ${{ env.GITHUB_TOKEN }} ${{ env.REPOSITORY }} ${{ env.ISSUE_NUMBER}} ${{ env.OPENAI_API_KEY }}
      shell: bash

    - name: Use own repo
      uses: witw20/AutoCoder@v1
      run: echo "Using own repo for testing"
      shell: bash
    
    
    - name: Commit files
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "autocoder-bot"
        git add .
        git commit -m "Add generated code from ChatGPT"
        git push origin HEAD:autocoder-branch-${{ inputs.ISSUE_NUMBER }}
      shell: bash
    
    - name: Create pull request
      uses: peter-evans/create-pull-request@v8
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        commit-message: "Add generated code from ChatGPT"
        title: "autocoder-branch-${{ github.event.issue.number }}"
        body: "This pull request contains code generated by ChatGPT based on the issue description."
        labels: "autocoder-bot"
        base: main
        branch: autocoder-branch-${{ github.event.issue.number }}

    - name: Complete job
      run: echo "Code generation process completed."
      shell: bash